<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url as CoreUrl;

/**
 * Implements hook_schema().
 */
function student_enrollment_schema() {
  $schema['student_enrollments'] = [
    'description' => 'Table for storing student enrollments for courses.',
    'fields' => [
      'user_id' => [
        'type' => 'int',
        'not null' => true,
        'description' => 'User ID of the enrolled user.',
      ],
      'course_id' => [
        'type' => 'int',
        'not null' => true,
        'description' => 'Course ID of the enrolled course.',
      ],
      'created' => [
        'type' => 'int',
        'not null' => true,
        'description' => 'The time when the enrollment was created.',
      ],
    ],
    'primary key' => ['user_id','course_id'],
    'indexes' => [
      'created' => ['created'],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function student_enrollment_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add reset password link.
  $url_object = CoreUrl::fromRoute('user.pass');
  $form['password_reset_link'] = [
    '#type' => 'link',
    '#url' => $url_object,
    '#title' => new TranslatableMarkup('Forgot your password?'),
    '#attributes' => [
      'class' => ['user-reset-password-link'],
    ],
  ];
}



/**
 * Implements hook_theme().
 */
function student_enrollment_theme() {
  return [
    'enrolled-courses-dashboard' => [
      'variables' => ['courses' => NULL],
    ],
    'enrollmentsTable' => [
      'variables' => ['enrollments' => NULL],
    ],
    'most-recent-courses' => [
      'variables' => ['courses' => NULL],
    ],
    'most-enrolled-courses' => [
      'variables' => ['courses' => NULL],
    ],
    'sorted-users-by-enrolled-courses' => [
      'variables' => ['users' => NULL],
    ],
  ];
}

